// Shared TLD reference data — loaded by domain-search.html and hosting-services.html.
// `restricted: true` marks sponsored/eligibility-gated TLDs (.gov/.mil/.arpa/.edu/.int/.bank)
// that Openprovider won't sell to the general public; these are excluded from any live
// availability-check list built from this catalog. Everything else is fair game to check.
var TLD_CATALOG = [
  { tld: '.com', type: 'gTLD', desc: 'Commercial; the universal standard for business websites.' },
  { tld: '.net', type: 'gTLD', desc: 'Network infrastructure; highly favored by tech and telecom.' },
  { tld: '.org', type: 'gTLD', desc: 'Organizations; standard for non-profits and open-source.' },
  { tld: '.arpa', type: 'Infrastructure', desc: 'Used exclusively for internal internet routing and DNS engineering.', restricted: true },
  { tld: '.edu', type: 'sTLD', desc: 'Accredited post-secondary educational institutions (primarily US).', restricted: true },
  { tld: '.gov', type: 'sTLD', desc: 'Reserved strictly for government entities (primarily US).', restricted: true },
  { tld: '.info', type: 'gTLD', desc: 'Information; a highly accessible unrestricted legacy extension.' },
  { tld: '.biz', type: 'gTLD', desc: 'Business alternative, created to alleviate .com overcrowding.' },
  { tld: '.mil', type: 'sTLD', desc: 'Restricted entirely to the United States Military.', restricted: true },
  { tld: '.int', type: 'sTLD', desc: 'International organizations established by treaty (e.g., UN, NATO).', restricted: true },
  { tld: '.cn', type: 'ccTLD', desc: 'China — highest-volume ccTLD.' },
  { tld: '.de', type: 'ccTLD', desc: 'Germany.' },
  { tld: '.uk', type: 'ccTLD', desc: 'United Kingdom.' },
  { tld: '.ru', type: 'ccTLD', desc: 'Russia.' },
  { tld: '.nl', type: 'ccTLD', desc: 'Netherlands.' },
  { tld: '.br', type: 'ccTLD', desc: 'Brazil.' },
  { tld: '.au', type: 'ccTLD', desc: 'Australia.' },
  { tld: '.fr', type: 'ccTLD', desc: 'France.' },
  { tld: '.it', type: 'ccTLD', desc: 'Italy.' },
  { tld: '.eu', type: 'ccTLD', desc: 'European Union.' },
  { tld: '.ca', type: 'ccTLD', desc: 'Canada.' },
  { tld: '.jp', type: 'ccTLD', desc: 'Japan.' },
  { tld: '.in', type: 'ccTLD', desc: 'India.' },
  { tld: '.co', type: 'ccTLD', desc: 'Colombia — massively used globally as a .com alternative.' },
  { tld: '.ai', type: 'ccTLD', desc: 'Anguilla — the definitive standard for artificial intelligence companies.' },
  { tld: '.io', type: 'ccTLD', desc: 'British Indian Ocean Territory — broadly adopted by SaaS/tech companies.' },
  { tld: '.us', type: 'ccTLD', desc: 'United States.' },
  { tld: '.ch', type: 'ccTLD', desc: 'Switzerland.' },
  { tld: '.se', type: 'ccTLD', desc: 'Sweden.' },
  { tld: '.pl', type: 'ccTLD', desc: 'Poland.' },
  { tld: '.es', type: 'ccTLD', desc: 'Spain.' },
  { tld: '.kr', type: 'ccTLD', desc: 'South Korea.' },
  { tld: '.tw', type: 'ccTLD', desc: 'Taiwan.' },
  { tld: '.mx', type: 'ccTLD', desc: 'Mexico.' },
  { tld: '.tv', type: 'ccTLD', desc: 'Tuvalu — widely used for media and video-streaming platforms.' },
  { tld: '.me', type: 'ccTLD', desc: 'Montenegro — frequently used for personal branding/blogs.' },
  { tld: '.cc', type: 'ccTLD', desc: 'Cocos Islands.' },
  { tld: '.tk', type: 'ccTLD', desc: 'Tokelau.' },
  { tld: '.vn', type: 'ccTLD', desc: 'Vietnam.' },
  { tld: '.tr', type: 'ccTLD', desc: 'Turkey.' },
  { tld: '.xyz', type: 'gTLD', desc: 'Heavily used for web3, tech experimentation, and general projects.' },
  { tld: '.top', type: 'gTLD', desc: 'Massive registration volume for budget-friendly generalized domains.' },
  { tld: '.online', type: 'gTLD', desc: 'A universal, multi-purpose alternative for web storefronts.' },
  { tld: '.site', type: 'gTLD', desc: 'Popular for landing pages and modern portfolio architectures.' },
  { tld: '.shop', type: 'gTLD', desc: 'Standard for independent e-commerce operations.' },
  { tld: '.store', type: 'gTLD', desc: 'Extensively used for retail brands and merchandise stores.' },
  { tld: '.tech', type: 'gTLD', desc: 'The go-to generic extension for engineering and software companies.' },
  { tld: '.app', type: 'gTLD', desc: 'Secure extension (requires HTTPS) widely used by application developers.' },
  { tld: '.dev', type: 'gTLD', desc: 'Secure extension optimized for developers and software engineering platforms.' },
  { tld: '.club', type: 'gTLD', desc: 'Used for community hubs, subscription models, and forums.' },
  { tld: '.vip', type: 'gTLD', desc: 'Popular in Asian markets for premium services.' },
  { tld: '.work', type: 'gTLD', desc: 'Frequently used for hiring boards, portfolios, and co-working spaces.' },
  { tld: '.space', type: 'gTLD', desc: 'Utilized by creative studios, designers, and freelance portfolios.' },
  { tld: '.live', type: 'gTLD', desc: 'The standard for real-time streaming platforms and broadcast networks.' },
  { tld: '.cloud', type: 'gTLD', desc: 'Extensively adopted by B2B SaaS and cloud computing infrastructure firms.' },
  { tld: '.pro', type: 'gTLD', desc: 'Tailored for certified professionals like accountants, lawyers, and consultants.' },
  { tld: '.digital', type: 'gTLD', desc: 'Used by marketing agencies and media entities.' },
  { tld: '.agency', type: 'gTLD', desc: 'Standard for design, advertising, and talent agencies.' },
  { tld: '.link', type: 'gTLD', desc: 'Favored for link-in-bio landing pages and shortening URLs.' },
  { tld: '.click', type: 'gTLD', desc: 'Highly popular for affiliate tracking and marketing performance links.' },
  { tld: '.coop', type: 'gTLD', desc: 'Cooperatives.' },
  { tld: '.bank', type: 'gTLD', desc: 'Highly restricted verification for financial institutions.', restricted: true },
  { tld: '.finance', type: 'gTLD', desc: 'Wealth management and fintech portals.' },
  { tld: '.ltd', type: 'gTLD', desc: 'Corporate legal structures.' },
  { tld: '.inc', type: 'gTLD', desc: 'Used by registered corporations.' },
  { tld: '.market', type: 'gTLD', desc: 'Marketplaces and trading sites.' },
  { tld: '.solutions', type: 'gTLD', desc: 'B2B consultancies.' },
  { tld: '.consulting', type: 'gTLD', desc: 'Management and IT consultancies.' },
  { tld: '.company', type: 'gTLD', desc: 'Multi-purpose corporate pages.' },
  { tld: '.business', type: 'gTLD', desc: 'B2B services and business information.' },
  { tld: '.studio', type: 'gTLD', desc: 'Design and photography workshops.' },
  { tld: '.media', type: 'gTLD', desc: 'News sites, publishers, and content hubs.' },
  { tld: '.design', type: 'gTLD', desc: 'UX/UI and graphic design portfolios.' },
  { tld: '.systems', type: 'gTLD', desc: 'Systems integration and backend infrastructure.' },
  { tld: '.network', type: 'gTLD', desc: 'Forum platforms and network hosting.' },
  { tld: '.software', type: 'gTLD', desc: 'Software application distribution channels.' },
  { tld: '.page', type: 'gTLD', desc: 'Minimalist single-page applications and blogs.' },
  { tld: '.blog', type: 'gTLD', desc: 'Individual publication platforms.' },
  { tld: '.photography', type: 'gTLD', desc: 'Visual creator galleries.' },
  { tld: '.global', type: 'gTLD', desc: 'International branding strategies.' },
  { tld: '.life', type: 'gTLD', desc: 'Wellness and lifestyle hubs.' },
  { tld: '.world', type: 'gTLD', desc: 'Broad community portals.' },
  { tld: '.guru', type: 'gTLD', desc: 'Subject matter experts and guides.' },
  { tld: '.today', type: 'gTLD', desc: 'Daily updates and time-sensitive media.' },
  { tld: '.news', type: 'gTLD', desc: 'Specialized journalistic content.' },
  { tld: '.expert', type: 'gTLD', desc: 'Individual professional consultants.' },
  { tld: '.boutique', type: 'gTLD', desc: 'Independent fashion or localized retail shops.' },
  { tld: '.events', type: 'gTLD', desc: 'Event scheduling, conferences, and booking engines.' },
  { tld: '.cool', type: 'gTLD', desc: 'General creative and consumer projects.' },
  { tld: '.london', type: 'geoTLD', desc: 'Businesses based in London, UK.' },
  { tld: '.nyc', type: 'geoTLD', desc: 'New York City-affiliated businesses.' },
  { tld: '.tokyo', type: 'geoTLD', desc: 'Regional Tokyo businesses.' },
  { tld: '.berlin', type: 'geoTLD', desc: 'Regional German ventures.' },
  { tld: '.paris', type: 'geoTLD', desc: 'French corporate and creative presence.' },
  { tld: '.amsterdam', type: 'geoTLD', desc: 'Local corporate entities in the Netherlands.' },
  { tld: '.miami', type: 'geoTLD', desc: 'Florida-centric travel and leisure markets.' },
  { tld: '.africa', type: 'geoTLD', desc: 'Regional African continent initiatives.' },
  { tld: '.asia', type: 'geoTLD', desc: 'Pan-Asian business operations.' },
  { tld: '.lat', type: 'geoTLD', desc: 'Latin American business target groups.' }
];
